version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network_authpluma

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./.env:/app/.env
    command: sh -c "migrate -path /app/internal/infrastructure/database/migration -database \"${DB_URL}\" up && /app/main"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL}
    networks:
      - network_authpluma

volumes:
  db_data:

networks:
  network_authpluma:
    driver: bridge