version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
    volumes:
      - ./.env:/app/.env
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  db_data: 