version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file: 
      - .env.${GO_ENV}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DB_URL}
    ports:
      - "${APP_PORT}:8080"

volumes:
  db_data: 